version: "3.7"

services:
  api:
    build: 
      context: ./api
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - D:/PMLDL_A1/models/catboost.pkl:/app/models/catboost.pkl

  web:
    build:
      context: ./app
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - api